### ISSUE TITLE
Mistakes in README

### ISSUE THREAD

**Issue by zenflow** [alex-shamshurin/sweetalert2-react#10]
- The new function to wrap a sweetalert2 instance is `asReactComponent`, not `withSwalInstance`
- "You should import sweetalert2.css from 'sweetalert2' package" no longer applies since #3 was closed

**Comment by alex-shamshurin** [comment]
It's was renamed to `withSwalInstance`.I think it's more reflective of what it does

**Comment by zenflow** [comment]
Ah.. Why wouldn't you bring that up in the PR?

In the PR it was originally `withSwal` and I indirectly suggested `asReactComponent` and @hipstersmoothie used it, so I assume we both agreed it was better.

Not that it is of great importance but...

I think `asReactComponent(mySwal)` is better because the expression can read like natural (human) language: `mySwal asReactComponent`. 

`withSwalInstance(mySwal)` seems kinda redundant ("swal instance" is usually indicated by the variable name), doesn't say *what* it's returning with the given swal instance (can be confusing since variable names for React components usually don't indicate "React component"), and doesn't read like natural language.

**Comment by alex-shamshurin** [comment]
`asReactComponent` seems for me to be a little confusing too. The package name is `sweetalert2-react` and any person use it expects he imports React component, not Anglular, no any other... So we do import react component 'as a react component'... Weird.  Also we do not export swal instance wrapped to react.

**Comment by zenflow** [comment]
Fair enough! That covers both points so I guess this can be closed.
