### ISSUE TITLE
Input type not working

### ISSUE THREAD

**Issue by AshotN** [alex-shamshurin/sweetalert2-react#17]
Setting the type to input doesn't bring the input field up.

`	
<SweetAlert show={this.state.renameAlert} title="Demo Input" text="SweetAlert in React" type="input" inputType="password" inputPlaceholder="password" onConfirm={inputValue=> {
    console.log(inputValue); // eslint-disable-line no-console
    this.setState({ renameAlert: false });
    }}
    />
`

produces

![image](https://user-images.githubusercontent.com/1350342/46118212-475aa200-c1ba-11e8-91f7-e10da83a70ae.png)

Also produces this error in console

> SweetAlert2: Unknown type! Expected "success", "error", "warning", "info" or "question", got "input"

**Comment by mrtsven** [comment]
It tells you exactly what is wrong
`type="input"` 
has to be
`type="succes"` or any other type that is expected.

**Comment by AshotN** [comment]
Ok then how would I go about getting an input

https://github.com/alex-shamshurin/sweetalert2-react/blob/master/examples/input/components/App.js this example doesn't work

**Comment by AshotN** [comment]
ok type=input is valid, i wasnt using the forked repo... im an idiot, we should update the readme to prevent this mistake in the future
