### ISSUE TITLE
Upgrade SweetAlert2

### ISSUE THREAD

**Issue by zenflow** [alex-shamshurin/sweetalert2-react#2]
This package currently uses SweetAlert2 version 6

https://github.com/alex-shamshurin/sweetalert2-react/blob/bc7374907abc79eb1788b70ed665d10354e36128/package.json#L68

The latest version of SweetAlert2 is 7.6.2

If/when tests are fixed (#1), [Greenkeeper](https://greenkeeper.io) can be used to do these upgrades (semi-) automatically.

**Comment by alex-shamshurin** [comment]
Thanks! PRs are welcome too!

**Comment by alex-shamshurin** [comment]
Yes, I have plans to do it this weekend.

**Comment by alex-shamshurin** [comment]
Upgraded
