### ISSUE TITLE
onCancel not called

### ISSUE THREAD

**Issue by mkurtzsd** [alex-shamshurin/sweetalert2-react#23]
I am pulling 0.8.1 from npm. I am finding that if I set an onConfirm handler, then my onCancel does not execute. Here's a snippet of my code:

import SweetAlert from 'sweetalert2-react';
....
          <SweetAlert
            show={this.state.removeAlert}
            title="Delete Swing"
            text="Are you sure?"
            showCancelButton
            confirmButtonColor="#bed745"
            onConfirm={() => { this.setState({ removeAlert: false }); dispatch(deleteSwing(this.state.swing)); }}
            onCancel={() => this.setState({ removeAlert: false, swing: null })}
          />

The deleteSwing() method is called regardless of whether I click the OK or Cancel buttons.

**Comment by alex-shamshurin** [comment]
Thanks, I'll check it out

**Comment by amirzarafshani** [comment]
same problem!

**Comment by alex-shamshurin** [comment]
PRs are welcome

**Comment by chrizLopez** [comment]
I'm having the same problem. Did any of you got the solution?

**Comment by mkurtzsd** [comment]
> I'm having the same problem. Did any of you got the solution?

I haven't personally had a chance to look into it further. Still hoping someone has the time. For now, we are building with sweetalert2-react v0.5.0.

**Comment by romulomessias** [comment]
I'm using  sweetalert2-react v0.8.1 with the same issue, any news about it?

**Comment by alex-shamshurin** [comment]
Ok, today I will take a look

**Comment by vBorgesAlb** [comment]
Same problem here, any update?

**Comment by Deepak2311** [comment]
` <SweetAlert
    show={this.state.openModal}
    title="Benutzer löschen"
    text="Bist du sicher, dass du löschen willst?"
    onConfirm={this.deleteLocation} 
    showCancelButton
    onCancel={() => this.setState({ openModal: false })}
    />                      
`
 onConfirm and on cancel both are working the same functionality...
please check once.

**Comment by zhangriyueming** [comment]
click cancel button will trigger onConfirm function, it's very dangerous

**Comment by garylevans** [comment]
Any update on this?

**Comment by Mahan-F** [comment]
@alex-shamshurin Is this part of the latest published version on NPM? I am on the latest version and this problem is still happening.

**Comment by douglasscriptore** [comment]
> @alex-shamshurin Is this part of the latest published version on NPM? I am on the latest version and this problem is still happening.

me too

**Comment by j-651** [comment]
+1

Same issue for me - `onCancel` is not being called using the NPM 0.8.3 version
