### ISSUE TITLE
Quick fix please: Typo give bug

### ISSUE THREAD

**Issue by indrainsignia** [alex-shamshurin/sweetalert2-react#28]
in
```
src/SweetAlert.js line 240 --> onConfirmm --> should be onConfirm
```
This bug prevent user from pressing the confirm button

**Comment by alex-shamshurin** [comment]
ok, typo

**Comment by oxlane** [comment]
could you fix this?

**Comment by alex-shamshurin** [comment]
PR please

**Comment by oxlane** [comment]
which branch?

**Comment by alex-shamshurin** [comment]
Master, I guess.

**Comment by oxlane** [comment]
still 'onConfirm is not defined'

**Comment by jcoon97** [comment]
This has been addressed in Pull Request #29 and awaiting review from @alex-shamshurin.

**Comment by Mahan-F** [comment]
Is this fix available on the current version that is available on NPM?
I am using the latest version and I still have this issue with `onConfirm` throwing an error.

**Comment by mastrix** [comment]
> Is this fix available on the current version that is available on NPM?
> I am using the latest version and I still have this issue with `onConfirm` throwing an error.

No fix was applied and [merged 21 days ago](https://github.com/alex-shamshurin/sweetalert2-react/pull/29/files)
And NPM package version was Published a month ago so this fix not available yet.

@alex-shamshurin, could you please update NPM package or say when you're going to update it?

Thanks

**Comment by alex-shamshurin** [comment]
Sorry guys, updated to 0.8.3

**Comment by alex-shamshurin** [comment]
@mastrix please check that you issue is solved
