### ISSUE TITLE
Import CSS to make it work

### ISSUE THREAD

**Issue by hipstersmoothie** [alex-shamshurin/sweetalert2-react#3]
I find it pretty odd that i have to include the css from another package to get your component to work. Is it possible to do that inside the component instead? I would expect importing your component to have already loaded it

**Comment by zenflow** [comment]
SweetAlert2 has a standalone build `sweetalert2.all.js` (and `sweetalert2.all.min.js`) that contains the css. In sweetalert2 version 7 that becomes the packages `main` module, so fixing #2 will automatically fix this and you won't have to include the css yourself.

**Comment by alex-shamshurin** [comment]
Closing, upgraded to sweetalert2  version 7
