### ISSUE TITLE
Integrate sweetalert2-react-content

### ISSUE THREAD

**Issue by hipstersmoothie** [alex-shamshurin/sweetalert2-react#4]
I know it's still young, but it would be awesome to include this so i could write

```js
<SweetAlert
  show={this.state.show}
  text={<h1> Some Text </h1>}
  onConfirm={() => this.setState({ show: false })}
/>
```

@zenflow do you think it would be possible to accomplish this with your package?

**Comment by zenflow** [comment]
@hipstersmoothie Like I said here https://github.com/zenflow/sweetalert2-react-content/issues/2#issuecomment-369823829

> You can use one, or the other, or (with a pending PR to sweetalert2-react, see zenflow/sweetalert2-react#1) both.

**Comment by zenflow** [comment]
Issue is in my fork because of zenflow/sweetalert2-react#2

**Comment by hipstersmoothie** [comment]
Okay now that i'm at a computer i can see all that. In my opinion this package is the perfect place to use your package to render the react content. As a use of the react component I would expect it to render react components out of the box without having to configure your package as well.

Trying to get them to both working together this is what I have so far but it's not working:

```js
import SweetAlert from 'sweetalert2-react'
import withReactContent from 'sweetalert2-react-content'
import 'sweetalert2/dist/sweetalert2.css'

const MySweetAlert = withReactContent(SweetAlert)

class Item extends Component {
  state = {
    modalOpen: false,
  }

  render() {
    return (
      <MySweetAlert
        show={this.state.modalOpen}
        text={<h1> Some Text </h1>}
        onConfirm={() => this.setState({ modalOpen: false })}
      />
    )
  }
}
```

I also tried 
```js
import SweetAlert from 'sweetalert2-react'
import withReactContent from 'sweetalert2-react-content'
import 'sweetalert2/dist/sweetalert2.css'

class Item extends Component {
  state = {
    modalOpen: false,
  }

  render() {
    return (
      <SweetAlert
        show={this.state.modalOpen}
        text={withReactContent(<h1> Some Text </h1>)}
        onConfirm={() => this.setState({ modalOpen: false })}
      />
    )
  }
}
```

Any suggestions on how to get them to play well together?

**Comment by zenflow** [comment]
> Any suggestions on how to get them to play well together?

@hipstersmoothie Yeah, read the comments on zenflow/sweetalert2-react#1 and make the necessary PR here.
