### ISSUE TITLE
Question: How/why is this package useful?

### ISSUE THREAD

**Issue by zenflow** [alex-shamshurin/sweetalert2-react#8]
The demo @ http://chentsulin.github.io/sweetalert-react/ uses code like this: (I've stripped it down a bit)

```jsx
import { Component } from 'react';
import SweetAlert from 'sweetalert-react';

export default class App extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      show: false,
    };
  }
  render() {
    return (
      <div>
        <button onClick={() => this.setState({ show: true })}>Alert</button>
        <SweetAlert
          show={this.state.show}
          title="Demo"
          showCancelButton
          onConfirm={() => {
            console.log('confirm');
            this.setState({ show: false });
          }}
          onCancel={() => {
            console.log('cancel');
            this.setState({ show: false });
          }}
          onEscapeKey={() => this.setState({ show: false })}
          onOutsideClick={() => this.setState({ show: false })}
        />
      </div>
    );
  }
}
```

But how is that more declarative (repo description is "Declarative SweetAlert in React") or better than this equivalent code?...

```jsx
import swal from 'sweetalert2';

function onClick () {
  swal({
    title: 'Demo',
    showCancelButton: true
  }).then(({dismiss}) => {
    if (!dismiss) {
      console.log('confirm')
    } else if (dismiss === 'cancel') {
      console.log('cancel')
    }
  })
}

export default function App {
    return <button onClick={onClick}>Alert</button>;
}
```

*note: The above code is using the SweetAlert2 version 7 API, where the `useRejections` option is false by default*

Using this package, it seems to take a lot more code to do the same thing. 

It bothers me that the `SweetAlert` component is technically present even when we don't want it to be, just hidden. I think this is the root of the problem of all the boilerplate code, because it means we have to manage the visibility and life-cycle of the swals ourselves.

I have the suspicion that swal as a component doesn't make sense...

/cc @alex-shamshurin @hipstersmoothie

**Comment by hipstersmoothie** [comment]
To me it makes sense even though there might be a little overhead. As a react developer i like things being components and having a little thought about being in React.

I agree with you that the swal component should probably not be in the dom all the time. We might want to take the same approach that the Material-UI modals do (they aren't rendered to the dom unless shown. Demo and source here: 

https://material-ui-next.com/api/modal/

I think we should move to an even more react-y state and do something like:

```
     <div>
        <Typography gutterBottom>Click to get the full Modal experience!</Typography>
        <Button onClick={this.handleOpen}>Open Modal</Button>
        <SweetAlert
          open={this.state.open}
          onClose={this.handleClose}
        >
          <div className={classes.paper}>
            <h2>
              Text in a modal
            </h2>
            <p id="simple-modal-description">
              Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
            </p>
          </div>
        </SweetAlert>
      </div>
```
(opened issue #9)

The one thing that doesn't make sense to when Swal is a component is the then. I haven't played around with trying to chain the Swal Components but I don't see how it would work out in my head.

**Comment by zenflow** [comment]
> To me it makes sense even though there might be a little overhead. As a react developer i like things being components and having a little thought about being in React.

@hipstersmoothie But why does *everything* need to be a React component? If not using a component results in simpler, more concise code, then isn't that better?

**Comment by hipstersmoothie** [comment]
I'd expect most everything that is related to the dom to be expressed through jsx.

If another developer were to come into my project with SweetAlert as just a function, it might be confusing finding the one place in my app where dom isn't expressed through jsx in a render function. Since this repo makes it a component I can keep all my jsx inside my render function and the outside developer wouldn't have to learn about a new api that defines jsx in an onclick callback. They would just look to the render function and see that the component can render a modal.

**Comment by illtrax** [comment]
@zenflow - If you want reusable code, then you want everything to be a component. If it's a small project that doesn't need to scale, then by all means, go for simple.

**Comment by alex-shamshurin** [comment]
The answer is - yes, this is a component. After all, it will be replaced with sweetalert in react version.
